name: CI
on:
  push:
    branches:
      - 'main'
      - '*'

jobs:

  # ----------------------------------------------------------------------------
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10.x'

      - uses: jiro4989/setup-nim-action@v1.0.2
        with:
          nim-version: '1.6.6'
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_dev.txt

      - name: Run tests
        run: |
          python -m pytest

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          python setup.py sdist
          python setup.py bdist_wheel
          python -c 'import os, glob; w=glob.glob("dist/*.whl")[0]; os.rename(w, w.replace("linux", "manylinux1"))'
          ls -l dist
          twine upload --non-interactive --skip-existing -r pypi -u __token__ dist/*

